### ISSUE TITLE
Probably some compatibility errors

### ISSUE THREAD

**Issue by novitae** [hot3eed/objtree#2]
I'm getting this issue.

It is probably due to things not compatible anymore, I tried many things, even changing a bit argparse program, but it always ended fucking up the parser or raising others issues.
```
Traceback (most recent call last):
  File "/Users/ae/objtree/launch.py", line 3, in <module>
    main()
  File "/Users/ae/objtree/objtree/cli.py", line 99, in main
    app = TestApplication()
  File "/usr/local/lib/python3.9/site-packages/frida_tools/application.py", line 108, in __init__
    options = parser.parse_args(real_args)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1827, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2579, in error
    self.print_usage(_sys.stderr)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2549, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2515, in format_usage
    return formatter.format_help()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 300, in _format_usage
    usage = usage % dict(prog=self._prog)
ValueError: unsupported format character 'p' (0x70) at index 8
```

**Comment by novitae** [comment]
From argparse
